### ISSUE TITLE
Some things copied from "standard" theme should be modified

### ISSUE THREAD

**Issue by rxtur** [atiq-cs/be_themes#1]
There are some things in site.master that copied from standard, but really need be modified for new theme. Like custom fields that should be removed of modified.

**Comment by atiq-cs** [comment]
Thanks. I am working on those. I will give new release after fixing and testing. Also, I need to acknowledge in the code properly to the "Standard Theme" creator.

An off topic. You might be able to help. I want to use azure blob storage with blogengine.net Do you think that is possible?

**Comment by rxtur** [comment]
I haven't used blob storage on Azure, you would probably have to implement your own provider for this, similar to others under BlogEngine.Core/Providers.

**Comment by atiq-cs** [comment]
The issue you mentioned should be fixed by now for BE 3.1
Haven't looked at BE 2.8 theme yet. Will have a look later.
